export interface TonfuraSettings {
  /** The Tonfura id that can be found in the Tonfura dashboard. */
  id?: number;

  /**
   * The Tonfura API key that can be found in the Tonfura dashboard.
   *
   * Defaults to: "demo" (a rate-limited public API key)
   */
  apiKey?: string;

  /**
   * The name of the network. Once configured, the network cannot be changed. To
   * use a different network, instantiate a new `Tonfura` instance.
   *
   * Defaults to: Network.ETH_MAINNET
   */
  network?: import('../constants').Network;

  /** The maximum number of retries to attempt if a request fails. Defaults to 5. */
  maxRetries?: number;

  /**
   * Optional URL endpoint to use for all requests. Setting this field will
   * override the URL generated by the {@link network} and {@link apiKey} fields.
   *
   * This field is useful for testing or for using a custom node endpoint. Note
   * that not all methods will work with custom URLs.
   */
  url?: string;
}
