name: Quality check
on:
  push:
    branches:
      - '**'
jobs:
  check:
    name: Lint and testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install modules
        run: |
          yarn
      - name: Lint
        run: |
          yarn lint
      - name: Unit Tests
        run: |
          yarn test
      # - name: Integration Tests
      #   run: |
      #     yarn test-integration
